import { MenuItem, NewsItem, User } from "./types";

import {
  Newspaper,
  AlertTriangle,
  FileText,
  ShieldPlus,
  Stethoscope,
  MessageCircleHeart,
  FileHeart,
  Building2,
  Ambulance,
  Laptop2,
  HeartHandshake,
  Award,
  Home,
  Info,
  Users,
  Utensils,
  Syringe,
  CalendarDays,
  Search,
} from "lucide-react";

export const users: Omit<User, "role">[] = [
  { full_name: "TS.BS Nguyễn Trọng Diện – Giám đốc", id: 1 },
  { full_name: "TS. Nguyễn Đình Hưng – Phó Giám đốc", id: 2 },
  { full_name: "TS. Trần Văn Chung – Phó Giám đốc", id: 3 },
  { full_name: "TS. Ông Vũ Cao Cương – Phó Giám đốc", id: 4 },
  { full_name: "Đ/c Đinh Hồng Phong  – Phó Giám đốc", id: 5 },
];

export const SERVICE_CATEGORIES = [
  {
    id: 1,
    title: "Tin tức – Sự kiện y tế",
    path: "/news/events",
    icon: Newspaper,
    containerClass:
      "bg-gradient-to-br from-blue-50 via-blue-100 to-blue-50 border-blue-200 hover:shadow-blue-300",
    iconBoxClass: "bg-blue-600 text-white shadow-blue-400/50",
    titleClass: "text-blue-900",
  },
  {
    id: 2,
    title: "Lịch công tác",
    // path: "http://lichcongtac.qnict.vn/sythanoi/",
    path: "/schedule",
    icon: CalendarDays,
    containerClass:
      "bg-gradient-to-br from-orange-50 via-orange-100 to-orange-50 border-orange-200 hover:shadow-orange-300",
    iconBoxClass: "bg-orange-500 text-white shadow-orange-400/50",
    titleClass: "text-orange-900",
  },
  {
    id: 3,
    title: "Chính sách y tế – Bảo hiểm y tế",
    path: "/policy",
    icon: FileText,
    containerClass:
      "bg-gradient-to-br from-indigo-50 via-indigo-100 to-indigo-50 border-indigo-200 hover:shadow-indigo-300",
    iconBoxClass: "bg-indigo-600 text-white shadow-indigo-400/50",
    titleClass: "text-indigo-900",
  },
  {
    id: 4,
    title: "Phản ánh - Y Tế",
    path: "/news/prevention",
    icon: ShieldPlus,
    containerClass:
      "bg-gradient-to-br from-emerald-50 via-emerald-100 to-emerald-50 border-emerald-200 hover:shadow-emerald-300",
    iconBoxClass: "bg-emerald-600 text-white shadow-emerald-400/50",
    titleClass: "text-emerald-900",
  },
  {
    id: 5,
    title: "Khám bệnh - chữa bệnh",
    path: "/news/examination",
    icon: Stethoscope,
    containerClass:
      "bg-gradient-to-br from-cyan-50 via-cyan-100 to-cyan-50 border-cyan-200 hover:shadow-cyan-300",
    iconBoxClass: "bg-cyan-600 text-white shadow-cyan-400/50",
    titleClass: "text-cyan-900",
  },
  {
    id: 6,
    title: "Tư vấn sức khỏe",
    path: "/consulting",
    icon: MessageCircleHeart,
    containerClass:
      "bg-gradient-to-br from-pink-50 via-pink-100 to-pink-50 border-pink-200 hover:shadow-pink-300",
    iconBoxClass: "bg-pink-500 text-white shadow-pink-400/50",
    titleClass: "text-pink-900",
  },
  {
    id: 7,
    title: "Hồ sơ sức khỏe toàn dân",
    path: "/health-records",
    icon: FileHeart,
    containerClass:
      "bg-gradient-to-br from-sky-50 via-sky-100 to-sky-50 border-sky-200 hover:shadow-sky-300",
    iconBoxClass: "bg-sky-600 text-white shadow-sky-400/50",
    titleClass: "text-sky-900",
  },
  {
    id: 8,
    title: "Hệ thống y tế Thủ đô",
    path: "/hanoi-system",
    icon: Building2,
    containerClass:
      "bg-gradient-to-br from-slate-50 via-slate-100 to-slate-50 border-slate-200 hover:shadow-slate-300",
    iconBoxClass: "bg-slate-600 text-white shadow-slate-400/50",
    titleClass: "text-slate-900",
  },
  {
    id: 9,
    title: "Trung tâm điều hành cấp cứu thông minh",
    path: "/emergency",
    icon: Ambulance,
    containerClass:
      "bg-gradient-to-br from-red-50 via-red-100 to-red-50 border-red-200 hover:shadow-red-300",
    iconBoxClass: "bg-red-600 text-white shadow-red-400/50",
    titleClass: "text-red-900",
  },
  {
    id: 10,
    title: "Chuyển đổi số",
    path: "/data-lookup",
    icon: Search,
    containerClass:
      "bg-gradient-to-br from-violet-50 via-violet-100 to-violet-50 border-violet-200 hover:shadow-violet-300",
    iconBoxClass: "bg-violet-600 text-white shadow-violet-400/50",
    titleClass: "text-violet-900",
  },
  {
    id: 11,
    title: "Bảo trợ xã hội",
    path: "/news/social",
    icon: HeartHandshake,
    containerClass:
      "bg-gradient-to-br from-teal-50 via-teal-100 to-teal-50 border-teal-200 hover:shadow-teal-300",
    iconBoxClass: "bg-teal-600 text-white shadow-teal-400/50",
    titleClass: "text-teal-900",
  },
  {
    id: 12,
    title: "Giám sát chất lượng dịch vụ y tế",
    path: "/news/good-deeds",
    icon: Award,
    containerClass:
      "bg-gradient-to-br from-yellow-50 via-yellow-100 to-yellow-50 border-yellow-200 hover:shadow-yellow-300",
    iconBoxClass: "bg-yellow-500 text-white shadow-yellow-400/50",
    titleClass: "text-yellow-900",
  },
];
export const SERVICE_CATEGORIES_FILTER = [
  {
    id: 1,
    title: "Tin tức – Sự kiện y tế",
    path: "/news/events",
  },
  {
    id: 2,
    title: "Cảnh báo y tế – Truyền thông nguy cơ",
    path: "/news/alerts",
  },
  {
    id: 3,
    title: "Khám bệnh - chữa bệnh",
    path: "/examination",
  },
  {
    id: 4,
    title: "Phòng bệnh – Nâng cao sức khỏe",
    path: "/news/prevention",
  },
  {
    id: 5,
    title: "Bảo trợ xã hội",
    path: "/news/examination",
  },
  {
    id: 6,
    title: "Chuyển đổi số",
    path: "/consulting",
  },
  {
    id: 7,
    title: "Chính sách y tế - bảo hiểm y tế",
    path: "/health-records",
  },
  {
    id: 8,
    title: "Gương người tốt – việc tốt ngành Y",
    path: "/good-deeds",
  },
];
export const MOCK_VIDEOS = [
  {
    id: "v1",
    title:
      "Bản tin Y tế Hà Nội: Toàn cảnh công tác phòng chống dịch tuần 1 tháng 1/2026",
    duration: "05:30",
    thumbnail: "https://picsum.photos/seed/video1/800/450",
    date: "07/01/2026",
  },
  {
    id: "v2",
    title:
      "Phóng sự: Những chiến sĩ áo trắng thầm lặng đêm Giao thừa Tết Bính Ngọ",
    duration: "08:45",
    thumbnail: "https://picsum.photos/seed/video2/800/450",
    date: "10/01/2026",
  },
  {
    id: "v3",
    title: "Hướng dẫn người dân sử dụng ứng dụng Hồ sơ sức khỏe điện tử",
    duration: "03:15",
    thumbnail: "https://picsum.photos/seed/video3/800/450",
    date: "02/01/2026",
  },
  {
    id: "v4",
    title: "Tọa đàm: Nâng cao chất lượng khám chữa bệnh tại y tế cơ sở",
    duration: "15:20",
    thumbnail: "https://picsum.photos/seed/video4/800/450",
    date: "28/12/2025",
  },
  {
    id: "v5",
    title: "Chuyên mục Sức khỏe: Phòng chống bệnh tiểu đường",
    duration: "10:00",
    thumbnail: "https://picsum.photos/seed/video5/800/450",
    date: "25/12/2025",
  },
];

export const MAIN_MENU: MenuItem[] = [
  { id: "home", title: "Trang chủ", path: "/", icon: Home },
  {
    id: "news",
    title: "Tin tức",
    path: "/news/events",
    icon: Newspaper,
    children: [
      {
        id: "news-events",
        title: "Tin tức – Sự kiện y tế",
        path: "/news/events",

        icon: Newspaper,
      },
      {
        id: "alerts",
        title: "Cảnh báo y tế - Truyền thông nguy cơ",
        path: "/news/alerts",
        icon: AlertTriangle,
      },
      {
        id: "good-deeds",
        title: "Gương người tốt – việc tốt",
        path: "/news/good-deeds",
        icon: Award,
      },
    ],
  },
  {
    id: "medical-pro",
    title: "Khám chữa bệnh",
    path: "/news/examination",
    icon: Stethoscope,
    children: [
      {
        id: "exam-general",
        title: "Thông tin khám chữa bệnh",
        path: "/news/examination",
        icon: Stethoscope,
      },
      {
        id: "food-safety",
        title: "Tư vấn sức khỏe",
        path: "/consulting",
        icon: Utensils,
      },
      {
        id: "population",
        title: "Hồ sơ sức khỏe toàn dân",
        path: "/health-records",
        icon: Users,
      },
    ],
  },
  { id: "policy", title: "Chính sách - BHYT", path: "/policy", icon: Info },
  {
    id: "system",
    title: "Hệ thống y tế",
    path: "/hanoi-system",
    icon: Building2,
    children: [
      {
        id: "system-network",
        title: "Mạng lưới cơ sở y tế",
        path: "/hanoi-system",
        icon: Building2,
      },
      {
        id: "emergency",
        title: "Trung tâm cấp cứu thông minh",
        path: "/emergency",
        icon: Ambulance,
      },
    ],
  },
  {
    id: "digital",
    title: "Chuyển đổi số",
    path: "/data-lookup",
    icon: Laptop2,
  },
  {
    id: "social-security",
    title: "An sinh xã hội",
    path: "/social-security",
    icon: Info,
  },
  {
    id: "guide",
    title: "Giới thiệu/Liên hệ",
    path: "#",
    icon: HeartHandshake,
    children: [
      {
        id: "work-schedule",
        // linkUrl :"http://lichcongtac.qnict.vn/sythanoi/",
        title: "Lịch công tác",
        path: "/schedule",
        icon: CalendarDays,
      },
      {
        id: "guide-exam",
        title: "Quy trình khám bệnh",
        path: "/guide/exam",
        icon: FileText,
      },
      {
        id: "guide-insurance",
        title: "Bảo hiểm y tế",
        path: "/policy",
        icon: ShieldPlus,
      },
      {
        id: "guide-vaccine",
        title: "Lịch tiêm chủng",
        path: "/guide/vaccine",
        icon: Syringe,
      },
    ],
  },
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 1,
    title: "Hà Nội triển khai thí điểm hồ sơ sức khỏe điện tử toàn dân",
    excerpt:
      "Sở Y tế Hà Nội vừa ban hành kế hoạch triển khai thí điểm lập hồ sơ sức khỏe điện tử cho người dân trên địa bàn 30 quận, huyện, thị xã nhằm nâng cao chất lượng quản lý sức khỏe cộng đồng.",
    date: "12/05/2024",
    image: "https://chuyendoiso.quangngai.gov.vn/items/cms/4347.jpg",
    category: "news-events",
    isFeatured: true,
  },
  {
    id: 2,
    title:
      "Cảnh báo dịch sốt xuất huyết có xu hướng gia tăng tại một số quận huyện",
    excerpt:
      "Theo Trung tâm Kiểm soát bệnh tật (CDC) Hà Nội, số ca mắc sốt xuất huyết trên địa bàn thành phố đang có dấu hiệu tăng nhanh tại các khu vực dân cư đông đúc.",
    date: "11/05/2024",
    image:
      "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?q=80&w=800&auto=format&fit=crop",
    category: "alerts",
  },
  {
    id: 3,
    title: "Bác sĩ Bệnh viện Xanh Pôn cứu sống bệnh nhân bị vỡ tạng do tai nạn",
    excerpt:
      "Các bác sĩ Khoa Ngoại tiêu hóa, Bệnh viện Đa khoa Xanh Pôn vừa thực hiện thành công ca phẫu thuật cấp cứu cho một bệnh nhân bị chấn thương bụng kín nghiêm trọng.",
    date: "10/05/2024",
    image:
      "https://images.unsplash.com/photo-1551076805-e1869033e561?q=80&w=800&auto=format&fit=crop",
    category: "good-deeds",
  },
  {
    id: 4,
    title:
      "Hà Nội tăng cường kiểm tra an toàn thực phẩm tại các bếp ăn trường học",
    excerpt:
      "Sở Y tế phối hợp với Sở Giáo dục và Đào tạo Hà Nội thành lập các đoàn kiểm tra liên ngành nhằm đảm bảo an toàn vệ sinh thực phẩm cho học sinh.",
    date: "09/05/2024",
    image:
      "https://images.unsplash.com/photo-1547573854-74d2a71d0826?q=80&w=800&auto=format&fit=crop",
    category: "news-events",
  },
  {
    id: 5,
    title:
      "Khám bệnh, phát thuốc miễn phí cho người cao tuổi tại huyện Sóc Sơn",
    excerpt:
      "Hơn 500 người cao tuổi tại xã Minh Phú, huyện Sóc Sơn đã được các y bác sĩ tình nguyện khám bệnh, tư vấn sức khỏe và cấp phát thuốc miễn phí.",
    date: "08/05/2024",
    image:
      "https://images.unsplash.com/photo-1581056771107-24ca5f033842?q=80&w=800&auto=format&fit=crop",
    category: "social",
  },
  {
    id: 6,
    title: "Thủ tục đăng ký bảo hiểm y tế hộ gia đình trực tuyến",
    excerpt:
      "Hướng dẫn chi tiết các bước đăng ký tham gia bảo hiểm y tế hộ gia đình qua cổng dịch vụ công quốc gia và ứng dụng VssID.",
    date: "07/05/2024",
    image:
      "https://images.unsplash.com/photo-1454165205744-3b78555e5572?q=80&w=800&auto=format&fit=crop",
    category: "policy",
  },
  {
    id: 7,
    title: "Lợi ích của việc tiêm chủng mở rộng đối với trẻ em",
    excerpt:
      "Tiêm chủng là biện pháp hiệu quả nhất để phòng ngừa các bệnh truyền nhiễm nguy hiểm ở trẻ nhỏ, giúp xây dựng hệ miễn dịch cộng đồng vững mạnh.",
    date: "06/05/2024",
    image:
      "https://images.unsplash.com/photo-1584362946444-1e7c4f9b7113?q=80&w=800&auto=format&fit=crop",
    category: "prevention",
  },
  {
    id: 8,
    title: "Chuyển đổi số ngành y tế: Bước tiến mới trong quản lý bệnh viện",
    excerpt:
      "Việc áp dụng bệnh án điện tử và hệ thống quản lý thông tin bệnh viện (HIS) giúp tối ưu hóa quy trình khám chữa bệnh và giảm thời gian chờ đợi của bệnh nhân.",
    date: "05/05/2024",
    image:
      "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop",
    category: "digital",
  },
];

export const MOCK_INTERNATIONAL = [
  {
    id: "i1",
    title:
      "WHO cảnh báo biến chủng cúm mới: Việt Nam chủ động giám sát ngay từ cửa khẩu",
    date: "13/01/2026",
    image: "https://picsum.photos/seed/inter1/600/400",
  },
  {
    id: "i2",
    title:
      "Hợp tác y tế Việt - Nhật: Chuyển giao công nghệ phẫu thuật nội soi bằng Robot",
    date: "09/01/2026",
    image: "https://picsum.photos/seed/inter2/600/400",
  },
  {
    id: "i3",
    title:
      'Các nước ASEAN thống nhất cơ chế "Hộ chiếu vắc xin" điện tử phiên bản 2.0',
    date: "28/12/2025",
    image: "https://picsum.photos/seed/inter3/600/400",
  },
];
export const MOCK_CULTURE = [
  {
    id: "s1",
    title:
      "Giải bóng đá Cup Sức khỏe Thủ đô 2026: Bệnh viện Thanh Nhàn vô địch",
    date: "14/01/2026",
    image: "https://picsum.photos/seed/sport1/600/400",
  },
  {
    id: "s2",
    title: "Hội thao ngành Y tế: Hơn 2.000 vận động viên tham gia chạy việt dã",
    date: "08/01/2026",
    image: "https://picsum.photos/seed/sport2/600/400",
  },
  {
    id: "s3",
    title:
      'Phong trào rèn luyện sức khỏe "Mỗi người dân đi bộ 10.000 bước mỗi ngày"',
    date: "01/01/2026",
    image: "https://picsum.photos/seed/sport3/600/400",
  },
];
export const MOCK_SPORTS = [
  {
    id: "s1",
    title:
      "Giải bóng đá Cup Sức khỏe Thủ đô 2026: Bệnh viện Thanh Nhàn vô địch",
    date: "14/01/2026",
    image: "https://picsum.photos/seed/sport1/600/400",
  },
  {
    id: "s2",
    title: "Hội thao ngành Y tế: Hơn 2.000 vận động viên tham gia chạy việt dã",
    date: "08/01/2026",
    image: "https://picsum.photos/seed/sport2/600/400",
  },
  {
    id: "s3",
    title:
      'Phong trào rèn luyện sức khỏe "Mỗi người dân đi bộ 10.000 bước mỗi ngày"',
    date: "01/01/2026",
    image: "https://picsum.photos/seed/sport3/600/400",
  },
];

export const CATEGORIES = [
  {
    id: 3,
    title: "Khám bệnh - chữa bệnh",
    icon: Stethoscope,
    iconColor: "text-pink-600",
    hoverColor: "text-pink-600",
    image: "https://suckhoethudo.vn/assets/kham benh-__1wzyZ_.png",
    data: [],
  },
  {
    id: 4,
    title: "Phòng bệnh - Nâng cao sức khỏe",
    icon: ShieldPlus,
    iconColor: "text-orange-500",
    hoverColor: "text-orange-600",
    image: "https://suckhoethudo.vn/assets/phong benh-CTWuljBT.png",
    data: [],
    paddingClass: "md:pl-8",
  },
  {
    id: 5,
    title: "Bảo trợ xã hội",
    icon: HeartHandshake,
    iconColor: "text-blue-500",
    hoverColor: "text-blue-600",
    image: "https://suckhoethudo.vn/assets/bao tro XH-By5fco0o.png",
    data: [],
    paddingClass: "md:pl-8",
  },
  {
    id: 6,
    title: "Chuyển đổi số y tế",
    icon: Laptop2,
    iconColor: "text-pink-600",
    hoverColor: "text-pink-600",
    image: "https://suckhoethudo.vn/assets/chuyen doi so-DSivldkT.png",
    data: [],
  },
  {
    id: 7,
    title: "Chính sách y tế - Bảo hiểm y tế",
    icon: FileText,
    iconColor: "text-orange-500",
    hoverColor: "text-orange-600",
    image: "https://suckhoethudo.vn/assets/chinh sach y te-C_dDpJVZ.png",
    data: [],
    paddingClass: "md:pl-8",
  },
  {
    id: 8,
    title: "Gương người tốt - việc tốt",
    icon: Award,
    iconColor: "text-blue-500",
    hoverColor: "text-blue-600",
    image: "https://suckhoethudo.vn/assets/guong nguoi tot-C7NJJGDV.png",
    data: [],
    paddingClass: "md:pl-8",
  },
];

export const capcuu = [
  {
    id: "AMB-1",
    plateNumber: "29A-11501",
    status: "BUSY",
    coords: [20.937454983400016, 106.02177631564803],
    driver: "Nguyễn Văn 1",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 29,
  },
  {
    id: "AMB-2",
    plateNumber: "29A-11502",
    status: "AVAILABLE",
    coords: [21.154913132483184, 106.08395929366134],
    driver: "Nguyễn Văn 2",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 59,
  },
  {
    id: "AMB-3",
    plateNumber: "29A-11503",
    status: "BUSY",
    coords: [21.046831124410662, 105.86904576606071],
    driver: "Nguyễn Văn 3",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 28,
  },
  {
    id: "AMB-4",
    plateNumber: "29A-11504",
    status: "BUSY",
    coords: [20.93853320979846, 106.05014803137576],
    driver: "Nguyễn Văn 4",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 50,
  },
  {
    id: "AMB-5",
    plateNumber: "29A-11505",
    status: "BUSY",
    coords: [20.758911801242185, 105.85827428515537],
    driver: "Nguyễn Văn 5",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 10,
  },
  {
    id: "AMB-6",
    plateNumber: "29A-11506",
    status: "AVAILABLE",
    coords: [20.87148082950425, 105.74308047378393],
    driver: "Nguyễn Văn 6",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 14,
  },
  {
    id: "AMB-7",
    plateNumber: "29A-11507",
    status: "AVAILABLE",
    coords: [20.99552398176946, 106.01858697274885],
    driver: "Nguyễn Văn 7",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 39,
  },
  {
    id: "AMB-8",
    plateNumber: "29A-11508",
    status: "AVAILABLE",
    coords: [20.815570827039856, 106.02655007326038],
    driver: "Nguyễn Văn 8",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 55,
  },
  {
    id: "AMB-9",
    plateNumber: "29A-11509",
    status: "AVAILABLE",
    coords: [21.2, 105.64769929405757],
    driver: "Nguyễn Văn 9",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-10",
    plateNumber: "29A-11510",
    status: "AVAILABLE",
    coords: [20.76009263986878, 105.70535710624523],
    driver: "Nguyễn Văn 10",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 2,
  },
  {
    id: "AMB-11",
    plateNumber: "29A-11511",
    status: "AVAILABLE",
    coords: [21.080175059924194, 105.80859028706544],
    driver: "Nguyễn Văn 11",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 32,
  },
  {
    id: "AMB-12",
    plateNumber: "29A-11512",
    status: "AVAILABLE",
    coords: [20.791037339659244, 105.53998533359352],
    driver: "Nguyễn Văn 12",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 34,
  },
  {
    id: "AMB-13",
    plateNumber: "29A-11513",
    status: "AVAILABLE",
    coords: [21.246835190405495, 106.00851810939294],
    driver: "Nguyễn Văn 13",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 59,
  },
  {
    id: "AMB-14",
    plateNumber: "29A-11514",
    status: "AVAILABLE",
    coords: [20.963657466120072, 105.77230802295252],
    driver: "Nguyễn Văn 14",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 24,
  },
  {
    id: "AMB-15",
    plateNumber: "29A-11515",
    status: "AVAILABLE",
    coords: [21.171868678349384, 105.67885812812402],
    driver: "Nguyễn Văn 15",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 19,
  },
  {
    id: "AMB-16",
    plateNumber: "29A-11516",
    status: "AVAILABLE",
    coords: [21.071268284175613, 105.95447632390395],
    driver: "Nguyễn Văn 16",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 0,
  },
  {
    id: "AMB-17",
    plateNumber: "29A-11517",
    status: "AVAILABLE",
    coords: [20.78307507291374, 105.96991731616716],
    driver: "Nguyễn Văn 17",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 5,
  },
  {
    id: "AMB-18",
    plateNumber: "29A-11518",
    status: "BUSY",
    coords: [20.880381095190945, 105.56754975657924],
    driver: "Nguyễn Văn 18",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 47,
  },
  {
    id: "AMB-19",
    plateNumber: "29A-11519",
    status: "AVAILABLE",
    coords: [21.195077958816036, 105.71006061509812],
    driver: "Nguyễn Văn 19",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-20",
    plateNumber: "29A-11520",
    status: "AVAILABLE",
    coords: [21.189492275971716, 106.05403103902316],
    driver: "Nguyễn Văn 20",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 21,
  },
  {
    id: "AMB-21",
    plateNumber: "29A-11521",
    status: "BUSY",
    coords: [21.037854012275957, 105.86105398429736],
    driver: "Nguyễn Văn 21",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 13,
  },
  {
    id: "AMB-22",
    plateNumber: "29A-11522",
    status: "AVAILABLE",
    coords: [21.045085543843793, 105.70629603421747],
    driver: "Nguyễn Văn 22",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 36,
  },
  {
    id: "AMB-23",
    plateNumber: "29A-11523",
    status: "AVAILABLE",
    coords: [20.96743885147622, 105.73423944451774],
    driver: "Nguyễn Văn 23",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 53,
  },
  {
    id: "AMB-24",
    plateNumber: "29A-11524",
    status: "AVAILABLE",
    coords: [20.964516586993536, 105.78144977328971],
    driver: "Nguyễn Văn 24",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 12,
  },
  {
    id: "AMB-25",
    plateNumber: "29A-11525",
    status: "BUSY",
    coords: [21.01657476701269, 105.74837579196206],
    driver: "Nguyễn Văn 25",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 35,
  },
  {
    id: "AMB-26",
    plateNumber: "29A-11526",
    status: "BUSY",
    coords: [20.98436942987216, 105.71690338474781],
    driver: "Nguyễn Văn 26",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 25,
  },
  {
    id: "AMB-27",
    plateNumber: "29A-11527",
    status: "AVAILABLE",
    coords: [20.989050100706653, 105.84347845798487],
    driver: "Nguyễn Văn 27",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 20,
  },
  {
    id: "AMB-28",
    plateNumber: "29A-11528",
    status: "AVAILABLE",
    coords: [21.04, 105.83010628373606],
    driver: "Nguyễn Văn 28",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 22,
  },
  {
    id: "AMB-29",
    plateNumber: "29A-11529",
    status: "AVAILABLE",
    coords: [21.01126262604279, 105.82545172915869],
    driver: "Nguyễn Văn 29",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 39,
  },
  {
    id: "AMB-30",
    plateNumber: "29A-11530",
    status: "AVAILABLE",
    coords: [21.00982624625811, 105.80411614308493],
    driver: "Nguyễn Văn 30",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 25,
  },
  {
    id: "AMB-31",
    plateNumber: "29A-11531",
    status: "AVAILABLE",
    coords: [21.004476681016776, 105.86144422123242],
    driver: "Nguyễn Văn 31",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 9,
  },
  {
    id: "AMB-32",
    plateNumber: "29A-11532",
    status: "BUSY",
    coords: [20.966679657118306, 105.70420305816808],
    driver: "Nguyễn Văn 32",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 44,
  },
  {
    id: "AMB-33",
    plateNumber: "29A-11533",
    status: "BUSY",
    coords: [20.959651672694086, 105.87387477306335],
    driver: "Nguyễn Văn 33",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-34",
    plateNumber: "29A-11534",
    status: "AVAILABLE",
    coords: [20.989249600510345, 105.71299372255368],
    driver: "Nguyễn Văn 34",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 16,
  },
  {
    id: "AMB-35",
    plateNumber: "29A-11535",
    status: "BUSY",
    coords: [20.969586324518925, 105.72333696571864],
    driver: "Nguyễn Văn 35",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 54,
  },
  {
    id: "AMB-36",
    plateNumber: "29A-11536",
    status: "AVAILABLE",
    coords: [21.014660202238257, 105.72716245332846],
    driver: "Nguyễn Văn 36",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 40,
  },
  {
    id: "AMB-37",
    plateNumber: "29A-11537",
    status: "AVAILABLE",
    coords: [21.006326794827785, 105.84320152152458],
    driver: "Nguyễn Văn 37",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 12,
  },
  {
    id: "AMB-38",
    plateNumber: "29A-11538",
    status: "AVAILABLE",
    coords: [20.995771498412548, 105.89116923122214],
    driver: "Nguyễn Văn 38",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 12,
  },
  {
    id: "AMB-39",
    plateNumber: "29A-11539",
    status: "AVAILABLE",
    coords: [20.96827025814269, 105.88021321740112],
    driver: "Nguyễn Văn 39",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 57,
  },
  {
    id: "AMB-40",
    plateNumber: "29A-11540",
    status: "AVAILABLE",
    coords: [21.016402865558703, 105.8533298027865],
    driver: "Nguyễn Văn 40",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 9,
  },
  {
    id: "AMB-41",
    plateNumber: "29A-11541",
    status: "BUSY",
    coords: [20.999504418535594, 105.73],
    driver: "Nguyễn Văn 41",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 35,
  },
  {
    id: "AMB-42",
    plateNumber: "29A-11542",
    status: "AVAILABLE",
    coords: [20.978512055522973, 105.82982545105583],
    driver: "Nguyễn Văn 42",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 6,
  },
  {
    id: "AMB-43",
    plateNumber: "29A-11543",
    status: "AVAILABLE",
    coords: [21.027654708174087, 105.71923328846272],
    driver: "Nguyễn Văn 43",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 36,
  },
  {
    id: "AMB-44",
    plateNumber: "29A-11544",
    status: "BUSY",
    coords: [20.970605568721133, 105.7245797045254],
    driver: "Nguyễn Văn 44",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 36,
  },
  {
    id: "AMB-45",
    plateNumber: "29A-11545",
    status: "AVAILABLE",
    coords: [21.02703924084159, 105.82689880071938],
    driver: "Nguyễn Văn 45",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 33,
  },
  {
    id: "AMB-46",
    plateNumber: "29A-11546",
    status: "AVAILABLE",
    coords: [20.95401980922146, 105.88678349785785],
    driver: "Nguyễn Văn 46",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 14,
  },
  {
    id: "AMB-47",
    plateNumber: "29A-11547",
    status: "AVAILABLE",
    coords: [20.954353377470373, 105.81258714882455],
    driver: "Nguyễn Văn 47",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 54,
  },
  {
    id: "AMB-48",
    plateNumber: "29A-11548",
    status: "AVAILABLE",
    coords: [20.972931408210123, 105.86043194559119],
    driver: "Nguyễn Văn 48",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 4,
  },
  {
    id: "AMB-49",
    plateNumber: "29A-11549",
    status: "BUSY",
    coords: [20.99615977103259, 105.79262418350127],
    driver: "Nguyễn Văn 49",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 2,
  },
  {
    id: "AMB-50",
    plateNumber: "29A-11550",
    status: "BUSY",
    coords: [20.97960837012413, 105.74213405171508],
    driver: "Nguyễn Văn 50",
    phone: "098.xxx.xxx",
    hospital: "BV Bạch Mai",
    speed: 2,
  },
];

export const ALL_FACILITIES = [
  {
    id: "cc-atvstp-hn",
    name: "Chi cục An toàn vệ sinh thực phẩm Hà Nội",
    type: "CC",
    category: "Chi cục",
    address: "35 P. Trần Bình, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437684024",
    coords: [21.0345, 105.7766],
    description: "Đơn vị quản lý nhà nước trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "cc-danso-treem",
    name: "Chi cục Dân số, Trẻ em và Phòng, chống tệ nạn xã hội",
    type: "CC",
    category: "Chi cục",
    address: "18 P. Sơn Tây, Phường Ba Đình, Thành phố Hà Nội",
    phone: "",
    coords: [21.033257171372412, 105.832770431185],
    description: "Đơn vị quản lý nhà nước trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-hadong",
    name: "Bệnh viện đa khoa Hà Đông",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 2 Bế Văn Đàn, Phường Hà Đông, Thành phố Hà Nội",
    phone: "02433824216",
    coords: [20.971, 105.7745],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-dongda",
    name: "Bệnh viện đa khoa Đống Đa",
    type: "BV",
    category: "Bệnh viện",
    address: "Ngõ 180 Nguyễn Lương Bằng, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02438517140",
    coords: [21.0157357, 105.8265407],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-bacthanglong",
    name: "Bệnh viện Bắc Thăng Long",
    type: "BV",
    category: "Bệnh viện",
    address: "Tổ 18, Thị trấn Đông Anh, Thành phố Hà Nội",
    phone: "02438832727",
    coords: [21.163, 105.858],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-thanhtri",
    name: "Bệnh viện đa khoa Thanh Trì",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 1 Tứ Hiệp, Xã Thanh Trì, Thành phố Hà Nội",
    phone: "02422182170",
    coords: [20.9487, 105.8457],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-hoenhai",
    name: "Bệnh viện đa khoa Hòe Nhai",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 34 Hòe Nhai, Phường Ba Đình, Thành phố Hà Nội",
    phone: "02439272980",
    coords: [21.0408, 105.846],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-donganh",
    name: "Bệnh viện đa khoa Đông Anh",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 1 Uy Nỗ, Xã Đông Anh, Thành phố Hà Nội",
    phone: "02438832450",
    coords: [21.1387, 105.853],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-vandinh",
    name: "Bệnh viện đa khoa Vân Đình",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 10 đường 22/8, Xã Vân Đình, Thành phố Hà Nội",
    phone: "02433882212",
    coords: [20.725, 105.7736],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-sontay",
    name: "Bệnh viện đa khoa Sơn Tây",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 304A Đường Lê Lợi, Phường Sơn Tây, Thành phố Hà Nội",
    phone: "0966401616",
    coords: [21.1518, 105.506],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-namthanglong",
    name: "Bệnh viện Nam Thăng Long",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 38 Tân Xuân, Phường Xuân Đỉnh, Thành phố Hà Nội",
    phone: "02438386009",
    coords: [21.079, 105.786],
    description: "Bệnh viện đa khoa công lập trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-phusan-hn",
    name: "Bệnh viện Phụ sản Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 929 Đường La Thành, Phường Giảng Võ, Thành phố Hà Nội",
    phone: "02438343181",
    coords: [21.0266308, 105.8069917],
    description: "Bệnh viện chuyên khoa sản phụ khoa trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-1",
    name: "Bệnh viện đa khoa Xanh Pôn",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 12 Chu Văn An, Phường Ba Đình, Thành phố Hà Nội",
    phone: "02438233075",
    coords: [21.031, 105.835],
    description:
      "Bệnh viện đa khoa đầu ngành Ngoại khoa và Nhi khoa của Thủ đô.",
  },
  {
    id: "bv-2",
    name: "Bệnh viện Thanh Nhàn",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 42 Thanh Nhàn, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "02439714363",
    coords: [21.0034756, 105.859],
    description:
      "Bệnh viện đa khoa hạng I, mũi nhọn về Nội khoa và hồi sức cấp cứu.",
  },
  {
    id: "bv-3",
    name: "Bệnh viện đa khoa Đức Giang",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 54 Trường Lâm, Phường Long Biên, Thành phố Hà Nội",
    phone: "02438271515",
    coords: [21.0613504, 105.898],
    description: "Cơ sở y tế hạng I khu vực phía Đông thành phố.",
  },
  {
    id: "bv-h1",
    name: "Bệnh viện đa khoa Ba Vì",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Tây Đằng, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.2152873, 105.41],
    description: "Phục vụ khám chữa bệnh cho nhân dân Ba Vì.",
  },
  {
    id: "bv-nhi-hn",
    name: "Bệnh viện Nhi Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Phố Nguyễn Trác, Phường Yên Nghĩa, Thành phố Hà Nội",
    phone: "0826722822",
    coords: [20.9615614, 105.7421047],
    description: "Bệnh viện chuyên khoa nhi trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-mat-hn",
    name: "Bệnh viện Mắt Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 37 Hai Bà Trưng, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "0848958866",
    coords: [21.0179738, 105.8065961],
    description: "Bệnh viện chuyên khoa mắt trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-tamthan-hn",
    name: "Bệnh viện Tâm thần Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Ngõ 467 Nguyễn Văn Linh, Phường Long Biên, Thành phố Hà Nội",
    phone: "02438276534",
    coords: [21.0342291, 105.91],
    description: "Bệnh viện chuyên khoa tâm thần (Trụ sở chính Sài Đồng)",
  },
  {
    id: "bv-dk-yhct-hn",
    name: "Bệnh viện đa khoa Y học cổ truyền Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 8 Phạm Hùng, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437684059",
    coords: [21.0342896, 105.78],
    description: "Bệnh viện y học cổ truyền trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-vn-cuba",
    name: "Bệnh viện Hữu nghị Việt Nam - Cu Ba",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 37 Hai Bà Trưng, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "0967671616",
    coords: [21.0246387, 105.8504],
    description: "Bệnh viện đa khoa chuyên khoa Răng Hàm Mặt, Tai Mũi Họng",
  },
  {
    id: "bv-phoi-hn",
    name: "Bệnh viện Phổi Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 44 Thanh Nhàn, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "0904599583",
    coords: [21.00358144509386, 105.85838321944107],
    description: "Bệnh viện chuyên khoa phổi trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-ungbuou-hn",
    name: "Bệnh viện Ung bướu Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 42A Thanh Nhàn, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "0915546116",
    coords: [21.004639583980214, 105.85919348878059],
    description: "Bệnh viện chuyên khoa ung bướu trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-tim-hn",
    name: "Bệnh viện Tim Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 92 Trần Hưng Đạo, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "02439427791",
    coords: [21.023868927370884, 105.8438897618363],
    description: "Bệnh viện chuyên khoa tim mạch trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-dalieuhn",
    name: "Bệnh viện Da liễu Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 79B Nguyễn Khuyến, Phường Đống Đa, Thành phố Hà Nội",
    phone: "19008186",
    coords: [21.028160697511055, 105.83858704705031],
    description: "Bệnh viện chuyên khoa da liễu trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-yhct-hadong",
    name: "Bệnh viện Y học cổ truyền Hà Đông",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 23 Nguyễn Lương Bằng, Phường Hà Đông, Thành phố Hà Nội",
    phone: "02433598363",
    coords: [20.97114368004001, 105.77148261512164],
    description: "Bệnh viện y học cổ truyền trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bv-tamthan-myduc",
    name: "Bệnh viện Tâm thần Mỹ Đức",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Lê Thanh, Xã Mỹ Đức, Thành phố Hà Nội",
    phone: "02433847226",
    coords: [20.80443841209088, 105.70326100470423],
    description: "Bệnh viện tâm thần chuyên khoa khu vực",
  },
  {
    id: "bv-than-hn",
    name: "Bệnh viện Thận Hà Nội",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 70 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02437757194",
    coords: [21.018880191245273, 105.80660026396501],
    description: "Bệnh viện chuyên khoa thận - tiết niệu",
  },
  {
    id: "bv-09",
    name: "Bệnh viện 09",
    type: "BV",
    category: "Bệnh viện",
    address: "Phố Tân Mai, Phường Tân Mai, Thành phố Hà Nội",
    phone: "02438641261",
    coords: [20.960713157268742, 105.80167114779451],
    description: "Bệnh viện chuyên khoa truyền nhiễm và điều trị HIV/AIDS",
  },
  {
    id: "bv-phcn",
    name: "Bệnh viện Phục hồi chức năng",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 35 Lê Văn Thiêm, Phường Giảng Võ, Thành phố Hà Nội",
    phone: "02432216229",
    coords: [20.999331257628043, 105.8047363573585],
    description: "Bệnh viện chuyên khoa phục hồi chức năng",
  },
  {
    id: "bv-maihuong",
    name: "Bệnh viện Tâm thần Ban ngày Mai Hương",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 4 Hồng Mai, Phường Hai Bà Trưng, Thành phố Hà Nội",
    phone: "02436275762",
    coords: [20.998978654141396, 105.85133517615384],
    description: "Bệnh viện tâm thần điều trị ban ngày",
  },
  {
    id: "bv-dk-socson",
    name: "Bệnh viện đa khoa Sóc Sơn",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Sóc Sơn, Xã Sóc Sơn, Thành phố Hà Nội",
    phone: "02435953784",
    coords: [21.24985585249886, 105.84715568861832],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-gialam",
    name: "Bệnh viện đa khoa huyện Gia Lâm",
    type: "BV",
    category: "Bệnh viện",
    address: "Số 135 Tố Hữu, Xã Gia Lâm, Thành phố Hà Nội",
    phone: "",
    coords: [21.00752965940591, 105.94413500522231],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-bavi",
    name: "Bệnh viện đa khoa huyện Ba Vì",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Chu Minh, Xã Ba Vì, Thành phố Hà Nội",
    phone: "02433863144",
    coords: [21.215512301918537, 105.40902947260938],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-thachthat",
    name: "Bệnh viện đa khoa huyện Thạch Thất",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Kim Quan, Xã Thạch Thất, Thành phố Hà Nội",
    phone: "02433842235",
    coords: [21.05095531897624, 105.56998430095148],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-quochoai",
    name: "Bệnh viện đa khoa huyện Quốc Oai",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Quốc Oai, Xã Quốc Oai, Thành phố Hà Nội",
    phone: "02433843144",
    coords: [20.991069179753023, 105.64383822078773],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-danphuong",
    name: "Bệnh viện đa khoa huyện Đan Phượng",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Phùng, Xã Đan Phượng, Thành phố Hà Nội",
    phone: "02433886223",
    coords: [21.087420868727445, 105.67112230317386],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-hoaideuc",
    name: "Bệnh viện đa khoa huyện Hoài Đức",
    type: "BV",
    category: "Bệnh viện",
    address: "Thôn Lũng Kênh, Xã Hoài Đức, Thành phố Hà Nội",
    phone: "02433861224",
    coords: [21.054239813441416, 105.70490406330637],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-chuongmy",
    name: "Bệnh viện đa khoa huyện Chương Mỹ",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Chúc Sơn, Phường Chương Mỹ, Thành phố Hà Nội",
    phone: "02433866124",
    coords: [20.92066129298143, 105.6983832742608],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-thanhoai",
    name: "Bệnh viện đa khoa huyện Thanh Oai",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Kim Bài, Xã Thanh Oai, Thành phố Hà Nội",
    phone: "02433873124",
    coords: [20.862334820459527, 105.75749136687786],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-myduc",
    name: "Bệnh viện đa khoa huyện Mỹ Đức",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Đại Nghĩa, Xã Mỹ Đức, Thành phố Hà Nội",
    phone: "02433847226",
    coords: [20.67961491835467, 105.75542049669869],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-thuongtin",
    name: "Bệnh viện đa khoa huyện Thường Tín",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Thường Tín, Xã Thường Tín, Thành phố Hà Nội",
    phone: "02433852224",
    coords: [20.86786223715064, 105.85918529260208],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-phuxuyen",
    name: "Bệnh viện đa khoa huyện Phú Xuyên",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Phú Xuyên, Xã Phú Xuyên, Thành phố Hà Nội",
    phone: "02433854224",
    coords: [20.72985450970312, 105.91446386020226],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-melinh",
    name: "Bệnh viện đa khoa huyện Mê Linh",
    type: "BV",
    category: "Bệnh viện",
    address: "Xã Mê Linh, Thành phố Hà Nội",
    phone: "02438161224",
    coords: [21.180577305453728, 105.68167653134986],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "bv-dk-phuctho",
    name: "Bệnh viện đa khoa huyện Phúc Thọ",
    type: "BV",
    category: "Bệnh viện",
    address: "Thị trấn Phúc Thọ, Xã Phúc Thọ, Thành phố Hà Nội",
    phone: "02433843224",
    coords: [21.103906317504915, 105.5570581048772],
    description: "Bệnh viện đa khoa hạng II tuyến huyện",
  },
  {
    id: "tt-1",
    name: "Trung tâm Kiểm soát bệnh tật (CDC) Hà Nội",
    type: "TT",
    category: "Trung tâm chuyên khoa",
    address: "Số 70 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02438343520",
    coords: [21.018727478832183, 105.8065992957797],
    description: "Đơn vị đầu ngành về y tế dự phòng và kiểm soát dịch bệnh.",
  },
  {
    id: "bt-1",
    name: "Làng trẻ em SOS Hà Nội",
    type: "BT",
    category: "Cơ sở bảo trợ",
    address: "Số 2 Doãn Kế Thiện, Phường Mai Dịch, Thành phố Hà Nội",
    phone: "02437644022",
    coords: [21.042362563429087, 105.77824791963384],
    description: "Nuôi dưỡng và chăm sóc trẻ em mồ côi, có hoàn cảnh đặc biệt.",
  },
  {
    id: "bt-115-hn",
    name: "Trung tâm Cấp cứu 115 Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 11 Phan Chu Trinh, Phường Cửa Nam, Thành phố Hà Nội",
    phone: "02438255612",
    coords: [21.022587756215778, 105.85649717427692],
    description: "Trung tâm cấp cứu ngoại viện của thành phố Hà Nội",
  },
  {
    id: "bt-cdc-hn",
    name: "Trung tâm Kiểm soát bệnh tật thành phố Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 70 Nguyễn Chí Thanh, Phường Đống Đa, Thành phố Hà Nội",
    phone: "02438343537",
    coords: [21.0232, 105.8105],
    description:
      "Trung tâm kiểm soát và phòng chống dịch bệnh của thành phố Hà Nội",
  },
  {
    id: "bt-kiemnghiem-hn",
    name: "Trung tâm Kiểm nghiệm thuốc, mỹ phẩm, thực phẩm Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address:
      "Số 7 ngõ 107 Nguyễn Chí Thanh, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
    phone: "02437737603",
    coords: [21.0158, 105.8062],
    description: "Trung tâm kiểm nghiệm thuốc, mỹ phẩm và thực phẩm",
    website: "https://kiemnghiemhanoi.gov.vn/",
  },
  {
    id: "bt-giamdinhy-hn",
    name: "Trung tâm Giám định y khoa Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address: "Số 86 Thợ Nhuộm, Phường Trần Hưng Đạo, Quận Hoàn Kiếm, Hà Nội",
    phone: "02437684024",
    coords: [21.0229, 105.8483], // Tọa độ thực tế tại Thợ Nhuộm
    description: "Trung tâm giám định y khoa trực thuộc Sở Y tế Hà Nội",
  },
  {
    id: "bt-phapy-hn",
    name: "Trung tâm Pháp y Hà Nội",
    type: "TT",
    category: "Trung tâm",
    address:
      "Chung cư B6A Nguyễn Chánh, KĐT Nam Trung Yên, Quận Cầu Giấy, Hà Nội",
    phone: "0975812499",
    coords: [21.0143, 105.7896],
    description: "Trung tâm pháp y phục vụ công tác giám định tư pháp",
    website: "http://phapyhanoi.vn/",
  },
  {
    id: "bt-btxh-1",
    name: "Trung tâm Bảo trợ xã hội 1 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Xuân Sơn, Thị xã Sơn Tây, Hà Nội",
    phone: "02433863074",
    coords: [21.1307, 105.4332],
    description: "Trung tâm bảo trợ xã hội trực thuộc thành phố Hà Nội",
    website: "https://trungtambaotroxahoi1hanoi.com/",
  },
  {
    id: "bt-btxh-2",
    name: "Trung tâm Bảo trợ xã hội 2 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Hoa Viên, Huyện Ứng Hòa, Hà Nội",
    phone: "02433771135",
    coords: [20.8072, 105.7144],
    description: "Trung tâm bảo trợ xã hội trực thuộc thành phố Hà Nội",
    website: "http://trungtambaotroxahoi2hanoi.com/",
  },
  {
    id: "bt-btxh-3",
    name: "Trung tâm Bảo trợ xã hội 3 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Tổ dân phố 3, Phường Tây Mỗ, Quận Nam Từ Liêm, Hà Nội",
    phone: "02438390187",
    coords: [21.0151, 105.7413], // Cập nhật cơ sở chính tại Tây Mỗ
    description: "Trung tâm bảo trợ xã hội trực thuộc thành phố Hà Nội",
  },
  {
    id: "bt-tttt-1",
    name: "Trung tâm Chăm sóc và Phục hồi chức năng người tâm thần số 1 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Thụy An, Huyện Ba Vì, Hà Nội",
    phone: "02462592915",
    coords: [21.1574, 105.4041], // Tọa độ thực tế tại Thụy An
    description: "Trung tâm chăm sóc và phục hồi chức năng người tâm thần",
    website: "https://ttcsvndnguoitamthan.gov.vn/",
  },
  {
    id: "bt-tttt-2",
    name: "Trung tâm Chăm sóc và Phục hồi chức năng người tâm thần số 2 Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Phú Sơn, Huyện Ba Vì, Hà Nội",
    phone: "02432008062",
    coords: [21.1984, 105.3742],
    description: "Trung tâm chăm sóc và phục hồi chức năng người tâm thần",
  },
  {
    id: "bt-khuyettat",
    name: "Trung tâm Chăm sóc người khuyết tật Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Xã Thụy An, Huyện Ba Vì, Hà Nội",
    phone: "0927135878",
    coords: [21.1555, 105.4058], // Cập nhật tọa độ chính xác tại Ba Vì
    description: "Trung tâm chăm sóc và hỗ trợ người khuyết tật",
  },
  {
    id: "bt-viet-han",
    name: "Trung tâm Phục hồi chức năng Việt - Hàn",
    type: "BT",
    category: "Trung tâm",
    address: "Thôn Yên Thái, Xã Phú Cát, Huyện Quốc Oai, Hà Nội",
    phone: "02433677466",
    coords: [20.9312, 105.5655],
    description: "Trung tâm phục hồi chức năng hợp tác Việt – Hàn",
  },
  {
    id: "bt-birla",
    name: "Làng Trẻ em Birla Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Số 4 Doãn Kế Thiện, Phường Mai Dịch, Quận Cầu Giấy, Hà Nội",
    phone: "02437644790",
    coords: [21.0416, 105.7788],
    description: "Cơ sở nuôi dưỡng và chăm sóc trẻ em có hoàn cảnh đặc biệt",
  },
  {
    id: "bt-tre-khuyettat",
    name: "Trung tâm Nuôi dưỡng trẻ khuyết tật Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Thị trấn Chúc Sơn, Huyện Chương Mỹ, Hà Nội",
    phone: "02433866124",
    coords: [20.9272, 105.7194],
    description: "Trung tâm nuôi dưỡng và chăm sóc trẻ khuyết tật",
  },
  {
    id: "bt-ctxh-treem",
    name: "Trung tâm Công tác xã hội và Quỹ Bảo trợ trẻ em Hà Nội",
    type: "BT",
    category: "Trung tâm",
    address: "Số 45 Bà Triệu, Phường Quang Trung, Quận Hà Đông, Hà Nội",
    phone: "02432233111",
    coords: [20.9685, 105.7821],
    description: "Trung tâm công tác xã hội và bảo trợ trẻ em",
    website: "http://ctxhvaqbtte.hanoi.gov.vn/",
  },

  // Trạm y tế xã, phường =====================================================================================================================
  //  =====================================================================================================================
  //  =====================================================================================================================
  //  =====================================================================================================================
  //  =====================================================================================================================

  {
    id: "tyt-an-khanh",
    name: "Trạm y tế xã An Khánh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn An Thọ, Xã An Khánh, Hà Nội",
    phone: "02433650432",
    coords: [21.0065, 105.7178],
    description: "Cơ sở y tế gần khu đô thị Splendora và Vinhomes Smart City",
  },
  {
    id: "tyt-truc-bach",
    name: "Trạm y tế phường Trúc Bạch",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 135 phố Trúc Bạch, Phường Trúc Bạch, Hà Nội",
    phone: "02438291410",
    coords: [21.0454, 105.8421],
    description: "Cơ sở y tế tuyến phường thuộc Quận Ba Đình",
  },
  {
    id: "tyt-ba-vi-xa",
    name: "Trạm y tế xã Ba Vì",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ba Vì, Hà Nội",
    phone: "",
    coords: [21.0652, 105.3884],
    description:
      "Cơ sở y tế tuyến xã phục vụ đồng bào các dân tộc vùng núi Ba Vì",
  },
  {
    id: "tyt-bach-mai",
    name: "Trạm y tế phường Bạch Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 39 Hồng Mai, Phường Bạch Mai, Hà Nội",
    phone: "02438631124",
    coords: [21.0025, 105.8518],
    description: "Cơ sở y tế tuyến phường thuộc Quận Hai Bà Trưng",
  },
  {
    id: "tyt-son-da",
    name: "Trạm y tế xã Sơn Đà",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Sơn Đà, Hà Nội",
    phone: "",
    coords: [21.1968, 105.3532],
    description: "Cơ sở y tế tuyến xã khu vực Bất Bạt cũ",
  },
  {
    id: "tyt-bat-trang",
    name: "Trạm y tế xã Bát Tràng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xóm 2 Bát Tràng, Xã Bát Tràng, Hà Nội",
    phone: "02438740333",
    coords: [20.9752, 105.9125],
    description: "Cơ sở y tế phục vụ khu vực làng nghề gốm sứ Bát Tràng",
  },
  {
    id: "tyt-binh-minh",
    name: "Trạm y tế xã Bình Minh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Bình Minh, Hà Nội",
    phone: "02433878436",
    coords: [20.8965, 105.7942],
    description: "Cơ sở y tế tuyến xã thuộc huyện Thanh Oai",
  },
  {
    id: "tyt-bo-de",
    name: "Trạm y tế phường Bồ Đề",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 154 phố Bồ Đề, Phường Bồ Đề, Hà Nội",
    phone: "02438723448",
    coords: [21.0338, 105.8782],
    description: "Cơ sở y tế tuyến phường thuộc Quận Long Biên",
  },
  {
    id: "tyt-quan-hoa",
    name: "Trạm y tế phường Quan Hoa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 167 đường Cầu Giấy, Phường Quan Hoa, Hà Nội",
    phone: "02438330310",
    coords: [21.0345, 105.7958],
    description: "Cơ sở y tế tuyến phường thuộc Quận Cầu Giấy",
  },
  {
    id: "tyt-chuong-duong-xa",
    name: "Trạm y tế xã Chương Dương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Chương Dương, Hà Nội",
    phone: "",
    coords: [20.8924, 105.8852],
    description: "Cơ sở y tế tuyến xã ven sông Hồng, huyện Thường Tín",
  },
  {
    id: "tyt-chuc-son",
    name: "Trạm y tế thị trấn Chúc Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 16 Khu hành chính, Thị trấn Chúc Sơn, Hà Nội",
    phone: "02433866115",
    coords: [20.9165, 105.7142],
    description: "Cơ sở y tế trung tâm huyện Chương Mỹ",
  },
  {
    id: "tyt-ha-bang",
    name: "Trạm y tế xã Hạ Bằng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hạ Bằng, Hà Nội",
    phone: "",
    coords: [21.0115, 105.5452],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-nguyen-trai-hadong",
    name: "Trạm y tế phường Nguyễn Trãi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 10 phố Lê Lợi, Phường Nguyễn Trãi, Hà Nội",
    phone: "02433824703",
    coords: [20.9725, 105.7758],
    description: "Cơ sở y tế trung tâm khu vực Hà Đông",
  },
  {
    id: "tyt-le-dai-hanh",
    name: "Trạm y tế phường Lê Đại Hành",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 25 Tạ Quang Bửu, Phường Lê Đại Hành, Hà Nội",
    phone: "02439764106",
    coords: [21.0118, 105.8495],
    description: "Cơ sở y tế tuyến phường thuộc Quận Hai Bà Trưng",
  },
  {
    id: "tyt-hat-mon",
    name: "Trạm y tế xã Hát Môn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hát Môn, Hà Nội",
    phone: "02433647413",
    coords: [21.1462, 105.5885],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Phúc Thọ",
  },
  {
    id: "tyt-thach-hoa",
    name: "Trạm y tế xã Thạch Hòa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thạch Hòa, Hà Nội",
    phone: "",
    coords: [20.9852, 105.5314],
    description: "Cơ sở y tế khu vực đô thị vệ tinh Hòa Lạc",
  },
  {
    id: "tyt-hoa-phu",
    name: "Trạm y tế xã Hòa Phú",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hòa Phú, Hà Nội",
    phone: "",
    coords: [20.8524, 105.6258],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Ứng Hòa",
  },
  {
    id: "tyt-hoa-xa",
    name: "Trạm y tế xã Hòa Xá",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hòa Xá, Hà Nội",
    phone: "02433984125",
    coords: [20.8062, 105.7854],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Ứng Hòa",
  },
  {
    id: "tyt-tram-troi",
    name: "Trạm y tế thị trấn Trạm Trôi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Trạm Trôi, Hà Nội",
    phone: "02433861254",
    coords: [21.0345, 105.7118],
    description: "Cơ sở y tế trung tâm huyện Hoài Đức",
  },
  {
    id: "tyt-hang-trong",
    name: "Trạm y tế phường Hàng Trống",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 25 Phố Ngô Quyền, Phường Hàng Trống, Hà Nội",
    phone: "02438253940",
    coords: [21.0285, 105.8521],
    description: "Cơ sở y tế tuyến phường thuộc Quận Hoàn Kiếm",
  },
  {
    id: "tyt-hoang-liet",
    name: "Trạm y tế phường Hoàng Liệt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 2 đường Ngọc Hồi, Phường Hoàng Liệt, Hà Nội",
    phone: "02438611116",
    coords: [20.9625, 105.8348],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Hoàng Mai",
  },
  {
    id: "tyt-hoang-mai-phuong",
    name: "Trạm y tế phường Hoàng Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 167 đường Hoàng Mai, Phường Hoàng Mai, Hà Nội",
    phone: "02438631181",
    coords: [20.9858, 105.8524],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Hoàng Mai",
  },
  {
    id: "tyt-hong-ha-phuong",
    name: "Trạm y tế phường Hồng Hà",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 469 đường Hồng Hà, Phường Phúc Tân, Hà Nội",
    phone: "02438257404",
    coords: [21.0312, 105.8595],
    description: "Cơ sở y tế khu vực ven sông Hồng, Hoàn Kiếm",
  },
  {
    id: "tyt-hong-son",
    name: "Trạm y tế xã Hồng Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hồng Sơn, Hà Nội",
    phone: "",
    coords: [20.7865, 105.7552],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Mỹ Đức",
  },
  {
    id: "tyt-hong-van",
    name: "Trạm y tế xã Hồng Vân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hồng Vân, Hà Nội",
    phone: "02433753112",
    coords: [20.8652, 105.8954],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thường Tín",
  },
  {
    id: "tyt-hung-dao",
    name: "Trạm y tế xã Hưng Đạo",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hưng Đạo, Hà Nội",
    phone: "",
    coords: [21.1442, 105.9021],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Đông Anh",
  },
  {
    id: "tyt-huong-son",
    name: "Trạm y tế xã Hương Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Hương Sơn, Hà Nội",
    phone: "02433847321",
    coords: [20.6215, 105.7508],
    description: "Cơ sở y tế phục vụ khu du lịch Chùa Hương",
  },
  {
    id: "tyt-khuong-dinh",
    name: "Trạm y tế phường Khương Đình",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 40 phố Khương Hạ, Phường Khương Đình, Hà Nội",
    phone: "02438551724",
    coords: [20.9865, 105.8152],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Thanh Xuân",
  },
  {
    id: "tyt-kien-hung",
    name: "Trạm y tế phường Kiến Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phố Kiến Hưng, Phường Kiến Hưng, Hà Nội",
    phone: "02433552085",
    coords: [20.9525, 105.7874],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Hà Đông",
  },
  {
    id: "tyt-dai-dong",
    name: "Trạm y tế xã Đại Đồng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đại Đồng, Hà Nội",
    phone: "",
    coords: [21.0262, 105.6154],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thạch Thất",
  },
  {
    id: "tyt-kim-anh",
    name: "Trạm y tế xã Thanh Xuân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Quốc lộ 2, Xã Thanh Xuân, Hà Nội",
    phone: "02438843512",
    coords: [21.2315, 105.8152],
    description: "Cơ sở y tế khu vực ngã ba Kim Anh",
  },
  {
    id: "tyt-kim-lien",
    name: "Trạm y tế phường Kim Liên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 15 Lương Định Của, Phường Kim Liên, Hà Nội",
    phone: "02438523122",
    coords: [21.0069, 105.8344],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-lang-ha",
    name: "Trạm y tế phường Láng Hạ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 10 Ngõ 122 Đường Láng, Phường Láng Hạ, Hà Nội",
    phone: "02438533630",
    coords: [21.0118, 105.8142],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-lien-minh",
    name: "Trạm y tế xã Liên Minh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Liên Minh, Hà Nội",
    phone: "",
    coords: [21.0942, 105.6724],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Đan Phượng",
  },
  {
    id: "tyt-linh-nam",
    name: "Trạm y tế phường Lĩnh Nam",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 471 đường Lĩnh Nam, Phường Lĩnh Nam, Hà Nội",
    phone: "02436444145",
    coords: [20.9765, 105.8824],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-long-bien",
    name: "Trạm y tế phường Long Biên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 1 Cổ Linh, Phường Long Biên, Hà Nội",
    phone: "02438751515",
    coords: [21.0264, 105.8928],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-me-linh",
    name: "Trạm y tế xã Mê Linh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn Hạ Lôi, Xã Mê Linh, Hà Nội",
    phone: "02438128038",
    coords: [21.1668, 105.7425],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Mê Linh",
  },
  {
    id: "tyt-minh-chau",
    name: "Trạm y tế xã Minh Châu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Minh Châu, Hà Nội",
    phone: "",
    coords: [21.2465, 105.5124],
    description: "Cơ sở y tế khu vực bãi giữa sông Hồng, Ba Vì",
  },
  {
    id: "tyt-my-duc",
    name: "Trạm y tế thị trấn Đại Nghĩa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Đại Nghĩa, Hà Nội",
    phone: "02433847246",
    coords: [20.7145, 105.7512],
    description: "Cơ sở y tế trung tâm huyện Mỹ Đức",
  },
  {
    id: "tyt-nam-phong",
    name: "Trạm y tế xã Nam Phong",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Nam Phong, Hà Nội",
    phone: "",
    coords: [20.6542, 105.8624],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Phú Xuyên",
  },
  {
    id: "tyt-nghia-do",
    name: "Trạm y tế phường Nghĩa Đô",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 60 Phố Nghĩa Đô, Phường Nghĩa Đô, Hà Nội",
    phone: "02438361093",
    coords: [21.0482, 105.8035],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ngoc-ha",
    name: "Trạm y tế phường Ngọc Hà",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 23 Ngõ 158 Ngọc Hà, Phường Ngọc Hà, Hà Nội",
    phone: "02438234390",
    coords: [21.0368, 105.8272],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-ngoc-hoi",
    name: "Trạm y tế xã Ngọc Hồi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Ngọc Hồi, Hà Nội",
    phone: "02438612143",
    coords: [20.9142, 105.8454],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thanh Trì",
  },
  {
    id: "tyt-noi-bai",
    name: "Trạm y tế xã Thanh Xuân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn Thạch Lỗi, Xã Thanh Xuân, Hà Nội",
    phone: "02438840303",
    coords: [21.2173, 105.7708],
    description: "Cơ sở y tế phục vụ nhân dân khu vực lân cận sân bay Nội Bài",
  },
  {
    id: "tyt-o-cho-dua",
    name: "Trạm y tế phường Ô Chợ Dừa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 106 Ngõ 34 Hoàng Cầu, Phường Ô Chợ Dừa, Hà Nội",
    phone: "02438515024",
    coords: [21.0205, 105.8245],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-trung-chau",
    name: "Trạm y tế xã Trung Châu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Trung Châu, Hà Nội",
    phone: "",
    coords: [21.1215, 105.6541],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-cat",
    name: "Trạm y tế xã Phú Cát",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phú Cát, Hà Nội",
    phone: "",
    coords: [20.9492, 105.5685],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-dien",
    name: "Trạm y tế phường Phú Diễn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 130 Phố Phú Diễn, Phường Phú Diễn, Hà Nội",
    phone: "02437638527",
    coords: [21.0454, 105.7658],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-dong",
    name: "Trạm y tế xã Phù Đổng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phù Đổng, Hà Nội",
    phone: "02438765412",
    coords: [21.0562, 105.9524],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-luong",
    name: "Trạm y tế phường Phú Lương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phố Bắc Lãm, Phường Phú Lương, Hà Nội",
    phone: "02433534125",
    coords: [20.9325, 105.7682],
    description: "Cơ sở y tế tuyến phường thuộc Quận Hà Đông",
  },
  {
    id: "tyt-phu-nghia",
    name: "Trạm y tế xã Phú Nghĩa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phú Nghĩa, Hà Nội",
    phone: "02433866223",
    coords: [20.9085, 105.6241],
    description: "Cơ sở y tế gần khu công nghiệp Phú Nghĩa",
  },
  {
    id: "tyt-phu-thuong",
    name: "Trạm y tế phường Phú Thượng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 15 Ngõ 15 An Dương Vương, Phường Phú Thượng, Hà Nội",
    phone: "02438385611",
    coords: [21.0885, 105.8114],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phu-xuyen",
    name: "Trạm y tế thị trấn Phú Xuyên",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Phú Xuyên, Hà Nội",
    phone: "02433854235",
    coords: [20.7415, 105.9128],
    description: "Cơ sở y tế trung tâm huyện Phú Xuyên",
  },
  {
    id: "tyt-phuc-lam",
    name: "Trạm y tế xã Phúc Lâm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phúc Lâm, Hà Nội",
    phone: "",
    coords: [20.7684, 105.7765],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-loi",
    name: "Trạm y tế phường Phúc Lợi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 279 Phố Phúc Lợi, Phường Phúc Lợi, Hà Nội",
    phone: "02438768114",
    coords: [21.0315, 105.9284],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-thinh",
    name: "Trạm y tế xã Đường Lâm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Đường Lâm, Hà Nội",
    phone: "",
    coords: [21.1442, 105.4851],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-phuc-tho",
    name: "Trạm y tế thị trấn Phúc Thọ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Phúc Thọ, Hà Nội",
    phone: "02433843224",
    coords: [21.1075, 105.5898],
    description: "Cơ sở y tế trung tâm huyện Phúc Thọ",
  },
  {
    id: "tyt-phuong-duc",
    name: "Trạm y tế xã Phượng Dực",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Phượng Dực, Hà Nội",
    phone: "",
    coords: [20.7645, 105.8504],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Phú Xuyên",
  },
  {
    id: "tyt-phuong-liet",
    name: "Trạm y tế phường Phương Liệt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 19 Phố Phương Liệt, Phường Phương Liệt, Hà Nội",
    phone: "02438645053",
    coords: [20.9947, 105.8402],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Thanh Xuân",
  },
  {
    id: "tyt-quang-bi",
    name: "Trạm y tế xã Quảng Bị",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Quảng Bị, Hà Nội",
    phone: "",
    coords: [20.8501, 105.6515],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Chương Mỹ",
  },
  {
    id: "tyt-quang-minh",
    name: "Trạm y tế thị trấn Quang Minh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Quang Minh, Hà Nội",
    phone: "02438134542",
    coords: [21.1868, 105.7952],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Mê Linh",
  },
  {
    id: "tyt-quang-oai",
    name: "Trạm y tế thị trấn Tây Đằng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Tây Đằng, Hà Nội",
    phone: "",
    coords: [21.2415, 105.4198],
    description: "Cơ sở y tế trung tâm huyện Ba Vì",
  },
  {
    id: "tyt-quoc-oai",
    name: "Trạm y tế thị trấn Quốc Oai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Quốc Oai, Hà Nội",
    phone: "02433843115",
    coords: [20.9902, 105.6385],
    description: "Cơ sở y tế trung tâm huyện Quốc Oai",
  },
  {
    id: "tyt-soc-son",
    name: "Trạm y tế thị trấn Sóc Sơn",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 16 Phố Miếu Thờ, Thị trấn Sóc Sơn, Hà Nội",
    phone: "02438840243",
    coords: [21.2585, 105.8475],
    description: "Cơ sở y tế trung tâm huyện Sóc Sơn",
  },
  {
    id: "tyt-son-dong",
    name: "Trạm y tế xã Sơn Đồng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Sơn Đồng, Hà Nội",
    phone: "02433861214",
    coords: [21.0185, 105.6984],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Hoài Đức",
  },
  {
    id: "tyt-son-tay",
    name: "Trạm y tế phường Quang Trung",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 1 Phố Quang Trung, Phường Quang Trung, Hà Nội",
    phone: "02433832158",
    coords: [21.1365, 105.5034],
    description: "Cơ sở y tế tuyến xã/phường khu vực Thị xã Sơn Tây",
  },
  {
    id: "tyt-suoi-hai",
    name: "Trạm y tế xã Cẩm Lĩnh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Cẩm Lĩnh, Hà Nội",
    phone: "",
    coords: [21.1712, 105.3625],
    description: "Cơ sở y tế khu vực hồ Suối Hai, Ba Vì",
  },
  {
    id: "tyt-tam-hung",
    name: "Trạm y tế xã Tam Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Tam Hưng, Hà Nội",
    phone: "02433976332",
    coords: [20.8872, 105.7954],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thanh Oai",
  },
  {
    id: "tyt-tay-ho",
    name: "Trạm y tế phường Xuân La",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 32B Phố Xuân La, Phường Xuân La, Hà Nội",
    phone: "02438361042",
    coords: [21.0632, 105.8094],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Tây Hồ",
  },
  {
    id: "tyt-tay-mo",
    name: "Trạm y tế phường Tây Mỗ",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phố Tây Mỗ, Phường Tây Mỗ, Hà Nội",
    phone: "02438390750",
    coords: [21.0015, 105.7428],
    description: "Cơ sở y tế tuyến xã/phường thuộc quận Nam Từ Liêm",
  },
  {
    id: "tyt-tay-phuong",
    name: "Trạm y tế xã Thạch Xá",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thạch Xá, Hà Nội",
    phone: "",
    coords: [21.0252, 105.6148],
    description: "Cơ sở y tế khu vực chùa Tây Phương",
  },
  {
    id: "tyt-tay-tuu",
    name: "Trạm y tế phường Tây Tựu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 66 phố Tây Tựu, Phường Tây Tựu, Hà Nội",
    phone: "02437638743",
    coords: [21.0664, 105.7225],
    description: "Cơ sở y tế tuyến phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thach-that",
    name: "Trạm y tế thị trấn Liên Quan",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Liên Quan, Hà Nội",
    phone: "02433842240",
    coords: [21.0616, 105.5714],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thạch Thất",
  },
  {
    id: "tyt-thanh-liet",
    name: "Trạm y tế xã Thanh Liệt",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 719 đường Thanh Liệt, Xã Thanh Liệt, Hà Nội",
    phone: "02436884024",
    coords: [20.9669, 105.8143],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thanh Trì",
  },
  {
    id: "tyt-thanh-oai",
    name: "Trạm y tế thị trấn Kim Bài",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 117 phố Kim Bài, Thị trấn Kim Bài, Hà Nội",
    phone: "02433873215",
    coords: [20.8758, 105.7825],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thanh Oai",
  },
  {
    id: "tyt-thanh-tri",
    name: "Trạm y tế phường Thanh Trì",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 431 đường Thanh Trì, Phường Thanh Trì, Hà Nội",
    phone: "02436445037",
    coords: [21.0002, 105.8978],
    description: "Cơ sở y tế tuyến phường thuộc quận Hoàng Mai",
  },
  {
    id: "tyt-thanh-xuan-nam",
    name: "Trạm y tế phường Thanh Xuân Nam",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Ngõ 495 đường Nguyễn Trãi, Phường Thanh Xuân Nam, Hà Nội",
    phone: "02438543419",
    coords: [20.9881, 105.7984],
    description: "Cơ sở y tế tuyến phường thuộc quận Thanh Xuân",
  },
  {
    id: "tyt-phu-tuc",
    name: "Trạm y tế xã Phú Túc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn Đường La, Xã Phú Túc, Hà Nội",
    phone: "",
    coords: [20.8145, 105.8502],
    description: "Cơ sở y tế tuyến xã khu vực Phú Xuyên",
  },
  {
    id: "tyt-thu-lam",
    name: "Trạm y tế xã Thụy Lâm",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn Thụy Lâm, Xã Thụy Lâm, Hà Nội",
    phone: "02438832598",
    coords: [21.1782, 105.9085],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Đông Anh",
  },
  {
    id: "tyt-thuan-an",
    name: "Trạm y tế xã Dương Xá",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Dương Xá, Hà Nội",
    phone: "02436785501",
    coords: [21.0094, 105.9732],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Gia Lâm",
  },
  {
    id: "tyt-thuong-cat",
    name: "Trạm y tế phường Thượng Cát",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phố Thượng Cát, Phường Thượng Cát, Hà Nội",
    phone: "02437510164",
    coords: [21.0965, 105.7172],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-thuong-phuc",
    name: "Trạm y tế xã Thượng Phúc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Thượng Phúc, Hà Nội",
    phone: "",
    coords: [20.8672, 105.8894],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Thường Tín",
  },
  {
    id: "tyt-thuong-tin",
    name: "Trạm y tế thị trấn Thường Tín",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Thường Tín, Hà Nội",
    phone: "02433852220",
    coords: [20.8715, 105.8608],
    description: "Cơ sở y tế trung tâm huyện Thường Tín",
  },
  {
    id: "tyt-tien-thang",
    name: "Trạm y tế xã Tiến Thắng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Tiến Thắng, Hà Nội",
    phone: "02438128038",
    coords: [21.2405, 105.7042],
    description: "Cơ sở y tế tuyến xã/phường thuộc huyện Mê Linh",
  },
  {
    id: "tyt-tran-phu",
    name: "Trạm y tế phường Trần Phú",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 205 đường khuyến lương, Phường Trần Phú, Hà Nội",
    phone: "02436446214",
    coords: [20.9754, 105.8892],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-trung-gia",
    name: "Trạm y tế xã Trung Giã",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Trung Giã, Hà Nội",
    phone: "02438850117",
    coords: [21.31422, 105.87221],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-lien-mac",
    name: "Trạm y tế phường Liên Mạc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Đường đê Liên Mạc, Phường Liên Mạc, Hà Nội",
    phone: "02438370123",
    coords: [21.08537, 105.75336],
    description: "Cơ sở y tế tuyến phường thuộc Quận Bắc Từ Liêm",
  },
  {
    id: "tyt-le-loi-son-tay",
    name: "Trạm y tế phường Lê Lợi",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 1 Lê Lợi, Phường Lê Lợi, Hà Nội",
    phone: "02433834117",
    coords: [21.14156, 105.50548],
    description: "Cơ sở y tế tuyến xã/phường khu vực Thị xã Sơn Tây",
  },
  {
    id: "tyt-tuong-mai",
    name: "Trạm y tế phường Tương Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 73 Nguyễn An Ninh, Phường Tương Mai, Hà Nội",
    phone: "02436620708",
    coords: [20.99086, 105.84531],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-van-dinh",
    name: "Trạm y tế thị trấn Vân Đình",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thị trấn Vân Đình, Hà Nội",
    phone: "02433882253",
    coords: [20.73272, 105.76798],
    description: "Cơ sở y tế trung tâm huyện Ứng Hòa",
  },
  {
    id: "tyt-ung-thien-cu",
    name: "Trạm y tế xã Sơn Công",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Sơn Công, Hà Nội",
    phone: "",
    coords: [20.78542, 105.82415],
    description: "Cơ sở y tế tuyến xã (khu vực Ứng Thiên cũ)",
  },
  {
    id: "tyt-van-mieu",
    name: "Trạm y tế phường Văn Miếu",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 130 Nguyễn Khuyến, Phường Văn Miếu, Hà Nội",
    phone: "02438435703",
    coords: [21.02871, 105.83732],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vat-lai",
    name: "Trạm y tế xã Vật Lại",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Vật Lại, Hà Nội",
    phone: "02433863451",
    coords: [21.20348, 105.40685],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-viet-hung",
    name: "Trạm y tế phường Việt Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Ngõ 139 Hoa Lâm, Phường Việt Hưng, Hà Nội",
    phone: "02438271222",
    coords: [21.05804, 105.89825],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vinh-hung",
    name: "Trạm y tế phường Vĩnh Hưng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 140 Vĩnh Hưng, Phường Vĩnh Hưng, Hà Nội",
    phone: "02436440265",
    coords: [20.98829, 105.87784],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-vinh-ngoc",
    name: "Trạm y tế xã Vĩnh Ngọc",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Thôn Vĩnh Thanh, Xã Vĩnh Ngọc, Hà Nội",
    phone: "02438835589",
    coords: [21.11418, 105.82795],
    description: "Cơ sở y tế tại thôn Vĩnh Thanh, xã Vĩnh Ngọc",
  },
  {
    id: "tyt-vinh-tuy",
    name: "Trạm y tế phường Vĩnh Tuy",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Ngõ 120 Vĩnh Tuy, Phường Vĩnh Tuy, Hà Nội",
    phone: "02438626615",
    coords: [20.99948, 105.87369],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-xuan-dinh",
    name: "Trạm y tế phường Xuân Đỉnh",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 2 Ngõ 207 Đường Xuân Đỉnh, Phường Xuân Đỉnh, Hà Nội",
    phone: "02438361094",
    coords: [21.0709, 105.7954],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-xuan-mai",
    name: "Trạm y tế thị trấn Xuân Mai",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Tiến Ân, Quốc lộ 6, Thị trấn Xuân Mai, Hà Nội",
    phone: "",
    coords: [20.9057, 105.5948],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-xuan-phuong",
    name: "Trạm y tế phường Xuân Phương",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Phố Thị Cấm, Phường Xuân Phương, Hà Nội",
    phone: "",
    coords: [21.0316, 105.7482],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-bai",
    name: "Trạm y tế xã Yên Bài",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Yên Bài, Hà Nội",
    phone: "",
    coords: [21.039, 105.4328],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-hoa",
    name: "Trạm y tế phường Yên Hòa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 228 Phố Trung Kính, Phường Yên Hòa, Hà Nội",
    phone: "02438332846",
    coords: [21.0232, 105.7908],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-lang",
    name: "Trạm y tế xã Yên Lãng",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Yên Lãng, Hà Nội",
    phone: "",
    coords: [21.1965, 105.7152],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-nghia",
    name: "Trạm y tế phường Yên Nghĩa",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 12 Ngõ 234 Quyết Thắng, Phường Yên Nghĩa, Hà Nội",
    phone: "02433570221",
    coords: [20.9545, 105.7375],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-so",
    name: "Trạm y tế phường Yên Sở",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Số 12 Hoàng Mai, Phường Yên Sở, Hà Nội",
    phone: "02438615452",
    coords: [20.9658, 105.8689],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
  {
    id: "tyt-yen-xuan",
    name: "Trạm y tế xã Tiến Xuân",
    type: "TYT",
    category: "Trạm y tế xã, phường",
    address: "Xã Tiến Xuân, Hà Nội",
    phone: "02439821168",
    coords: [20.9702, 105.494],
    description: "Cơ sở y tế tuyến xã/phường thuộc hệ thống y tế cơ sở Hà Nội",
  },
];
